[application]
# App (Project) Name
name = "Orderbook"

[web.app]
# HTML title tag content
title = "Orderbook"
icon = "assets/lob.png"

[web.watcher]

[bundle]
identifier = "ksahoo"
publisher = "KamleshSahoo"
icon = ["assets/lob.png", "assets/lob.icns", "assets/lob.ico"]

[web.resource]
script = []

[web.resource.dev]
script = []