[application]

# App (Project) Name
name = "frontend"

[web.app]

# HTML title tag content
title = "frontend"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = [
    "https://cdn.jsdelivr.net/npm/echarts@5.5.1/dist/echarts.min.js",
    "https://cdn.jsdelivr.net/npm/echarts-gl@2.0.9/dist/echarts-gl.min.js",
]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
